SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `Kick_Log` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `KickReason` text NOT NULL,
  `KickDate` varchar(16) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;

CREATE TABLE IF NOT EXISTS `Ban_Log` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BanReason` text NOT NULL,
  `BanDate` varchar(16) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;